# Generated by Django 5.1.6 on 2026-02-08 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system', models.CharField(choices=[('payroll', 'Payroll API'), ('sars', 'SARS e-Filing'), ('velocity_trade', 'Velocity Trade'), ('banking', 'Banking (EFT/NAEDO)'), ('jse', 'JSE'), ('sens', 'SENS')], db_index=True, max_length=20)),
                ('operation', models.CharField(help_text="e.g., 'submit_tax_directive', 'sync_employees', 'execute_trade'", max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('retrying', 'Retrying')], db_index=True, default='pending', max_length=20)),
                ('request_data', models.JSONField(blank=True, default=dict, help_text='Sanitised request payload (no secrets/tokens).')),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Response payload from external system.')),
                ('response_code', models.IntegerField(blank=True, help_text='HTTP status code or system-specific code.', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reference_model', models.CharField(blank=True, max_length=100)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Unique key to prevent duplicate calls.', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['company', 'system', 'status'], name='integration_company_7a9cb7_idx'), models.Index(fields=['system', 'operation', 'started_at'], name='integration_system_10c4d5_idx'), models.Index(fields=['reference_model', 'reference_id'], name='integration_referen_03b7f5_idx')],
            },
        ),
    ]
