# Generated by Django 5.1.6 on 2026-02-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSECompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, help_text="JSE ticker symbol (e.g. 'SOL', 'NPN', 'ANG').", max_length=10, unique=True)),
                ('company_name', models.CharField(db_index=True, help_text='Full registered company name.', max_length=255)),
                ('isin', models.CharField(blank=True, help_text='International Securities Identification Number.', max_length=12)),
                ('sector', models.CharField(blank=True, help_text="JSE sector classification (e.g. 'Mining', 'Financial Services').", max_length=100)),
                ('market_cap_category', models.CharField(blank=True, help_text='Large Cap, Mid Cap, Small Cap, etc.', max_length=20)),
                ('registration_number', models.CharField(blank=True, help_text='CIPC registration number if known.', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the listing is currently active on JSE.')),
                ('last_enriched_at', models.DateTimeField(blank=True, help_text='When live data was last fetched from Yahoo Finance.', null=True)),
                ('share_price', models.DecimalField(blank=True, decimal_places=2, help_text='Last fetched share price in ZAR.', max_digits=12, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, help_text='Market capitalisation in ZAR.', null=True)),
            ],
            options={
                'verbose_name': 'JSE Listed Company',
                'verbose_name_plural': 'JSE Listed Companies',
                'ordering': ['company_name'],
                'indexes': [models.Index(fields=['ticker', 'is_active'], name='integration_ticker_0066f8_idx'), models.Index(fields=['company_name', 'is_active'], name='integration_company_04e706_idx')],
            },
        ),
    ]
