# Generated by Django 5.1.6 on 2026-02-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_company_501eb2_idx',
            old_name='documents_do_company_idx_cat',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_company_f009e1_idx',
            old_name='documents_do_company_idx_sta',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_benefic_5f7a9b_idx',
            old_name='documents_do_benefic_idx_cat',
        ),
    ]
