# Generated by Django 5.1.6 on 2026-02-08 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(help_text='Company registration number (e.g. CIPC number).', max_length=50, unique=True)),
                ('tax_number', models.CharField(blank=True, help_text='Company tax reference number.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('scheme_name', models.CharField(blank=True, max_length=255)),
                ('trust_name', models.CharField(blank=True, max_length=255)),
                ('trust_bank_account', models.CharField(blank=True, help_text='Trust bank account number for dividend distributions.', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
