# Generated by Django 5.1.6 on 2026-02-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='jse_isin',
            field=models.CharField(blank=True, help_text="ISIN code for the company's listed shares.", max_length=12),
        ),
        migrations.AddField(
            model_name='company',
            name='jse_ticker',
            field=models.CharField(blank=True, help_text='JSE ticker symbol if the company is listed.', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.CharField(blank=True, help_text="Industry sector (e.g. 'Mining', 'Technology').", max_length=100),
        ),
    ]
