# Generated by Django 5.1.6 on 2026-02-08 11:56

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0002_beneficiary_leaver_type'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthEndRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_year', models.PositiveSmallIntegerField(help_text='Year of the period (e.g. 2025).')),
                ('period_month', models.PositiveSmallIntegerField(help_text='Month of the period (1-12).', validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(help_text="e.g. 'January 2025 Month-End'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('idempotency_key', models.CharField(help_text="Unique key to prevent duplicate runs (e.g. 'COMPANY-2025-01').", max_length=255, unique=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('total_shares_vested', models.PositiveIntegerField(default=0)),
                ('total_shares_sold', models.PositiveIntegerField(default=0)),
                ('total_gross_proceeds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_net_proceeds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('vesting_event_count', models.PositiveIntegerField(default=0)),
                ('termination_count', models.PositiveIntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='month_end_runs_approved', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='month_end_runs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxDirective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('directive_number', models.CharField(blank=True, help_text='SARS tax directive number once received.', max_length=50)),
                ('tax_year', models.PositiveSmallIntegerField(help_text='Tax year (e.g. 2025 for 2024/2025 tax year).')),
                ('request_date', models.DateField(blank=True, help_text='Date directive was requested from SARS.', null=True)),
                ('response_date', models.DateField(blank=True, help_text='Date response was received from SARS.', null=True)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Taxable amount as per SARS directive.', max_digits=16)),
                ('directive_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Tax rate specified in directive (e.g. 0.3500 = 35%).', max_digits=5, null=True)),
                ('calculated_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax calculated per directive.', max_digits=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested from SARS'), ('received', 'Received'), ('declined', 'Declined by SARS'), ('not_required', 'Not Required')], db_index=True, default='pending', max_length=20)),
                ('decline_reason', models.TextField(blank=True, help_text='Reason if directive was declined by SARS.')),
                ('notes', models.TextField(blank=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_directives', to='beneficiaries.beneficiary')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('run', models.ForeignKey(blank=True, help_text='Associated month-end run (optional).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_directives', to='month_end.monthendrun')),
            ],
            options={
                'ordering': ['-request_date', 'beneficiary__last_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VestingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('scheduled', 'Scheduled Vesting'), ('sale', 'Share Sale'), ('forfeiture', 'Forfeiture (Termination)'), ('transfer', 'Transfer')], db_index=True, max_length=20)),
                ('event_date', models.DateField(help_text='Date when the event occurred or is scheduled.')),
                ('shares_affected', models.PositiveIntegerField(help_text='Number of shares affected by this event.')),
                ('shares_before', models.PositiveIntegerField(help_text='Vested shares before this event.')),
                ('shares_after', models.PositiveIntegerField(help_text='Vested shares after this event.')),
                ('share_price', models.DecimalField(blank=True, decimal_places=4, help_text='Price per share at sale (ZAR).', max_digits=12, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vesting_events', to='beneficiaries.beneficiary')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vesting_events', to='month_end.monthendrun')),
            ],
            options={
                'ordering': ['-event_date', 'beneficiary__last_name'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='monthendrun',
            index=models.Index(fields=['company', 'status'], name='month_end_m_company_8357b5_idx'),
        ),
        migrations.AddIndex(
            model_name='monthendrun',
            index=models.Index(fields=['company', 'period_year', 'period_month'], name='month_end_m_company_ad3b05_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthendrun',
            constraint=models.CheckConstraint(condition=models.Q(('period_month__gte', 1), ('period_month__lte', 12)), name='valid_period_month'),
        ),
        migrations.AddIndex(
            model_name='taxdirective',
            index=models.Index(fields=['beneficiary', 'tax_year'], name='month_end_t_benefic_302d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='taxdirective',
            index=models.Index(fields=['status', 'request_date'], name='month_end_t_status_7947ed_idx'),
        ),
        migrations.AddIndex(
            model_name='vestingevent',
            index=models.Index(fields=['run', 'event_type'], name='month_end_v_run_id_ad0b76_idx'),
        ),
        migrations.AddIndex(
            model_name='vestingevent',
            index=models.Index(fields=['beneficiary', 'event_date'], name='month_end_v_benefic_f4d13e_idx'),
        ),
    ]
