# Generated by Django 5.1.6 on 2026-02-08 09:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('beneficiary_create', 'Beneficiary Created'), ('beneficiary_update', 'Beneficiary Updated'), ('beneficiary_delete', 'Beneficiary Deleted'), ('bank_detail_change', 'Bank Detail Changed'), ('dividend_run_create', 'Dividend Run Created'), ('dividend_run_state_change', 'Dividend Run State Change'), ('dividend_allocation_apply', 'Dividend Allocation Applied'), ('month_end_run_create', 'Month-End Run Created'), ('month_end_run_state_change', 'Month-End Run State Change'), ('file_upload', 'File Uploaded'), ('file_download', 'File Downloaded'), ('payment_file_generated', 'Payment File Generated'), ('manual_override', 'Manual Override'), ('integration_call', 'Integration Call'), ('integration_response', 'Integration Response')], db_index=True, max_length=50)),
                ('target_model', models.CharField(blank=True, db_index=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['company', 'action', 'timestamp'], name='audit_audit_company_430c8d_idx'), models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['target_model', 'target_id'], name='audit_audit_target__573821_idx')],
            },
        ),
    ]
