# Generated by Django 5.1.6 on 2026-02-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('beneficiary_create', 'Beneficiary Created'), ('beneficiary_update', 'Beneficiary Updated'), ('beneficiary_delete', 'Beneficiary Deleted'), ('bank_detail_change', 'Bank Detail Changed'), ('dividend_run_create', 'Dividend Run Created'), ('dividend_run_state_change', 'Dividend Run State Change'), ('dividend_allocation_apply', 'Dividend Allocation Applied'), ('month_end_run_create', 'Month-End Run Created'), ('month_end_run_state_change', 'Month-End Run State Change'), ('file_upload', 'File Uploaded'), ('file_download', 'File Downloaded'), ('payment_file_generated', 'Payment File Generated'), ('manual_override', 'Manual Override'), ('company_create', 'Company Created'), ('integration_call', 'Integration Call'), ('integration_response', 'Integration Response')], db_index=True, max_length=50),
        ),
    ]
