# Generated by Django 5.1.6 on 2026-02-08 11:22

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="e.g. 'FY2025 Final Dividend'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total dividend pool in ZAR.', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('dividend_per_share', models.DecimalField(decimal_places=6, help_text='Dividend amount per share (ZAR).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('dwt_rate', models.DecimalField(decimal_places=4, default=Decimal('0.20'), help_text='Dividend Withholding Tax rate (e.g. 0.2000 = 20%).', max_digits=5)),
                ('record_date', models.DateField(help_text='Date on which share register is frozen for this dividend.')),
                ('payment_date', models.DateField(help_text='Date on which payments will be made.')),
                ('declaration_date', models.DateField(blank=True, help_text='Date the dividend was declared by the board.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('idempotency_key', models.CharField(help_text="Unique key to prevent duplicate runs (e.g. 'COMPANY-FY2025-FINAL').", max_length=255, unique=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('allocation_count', models.PositiveIntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dividend_runs_approved', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividend_runs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DividendAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shares_at_record_date', models.PositiveIntegerField(help_text='Number of vested shares held on the record date.')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividend_allocations', to='beneficiaries.beneficiary')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='dividends.dividendrun')),
            ],
            options={
                'ordering': ['beneficiary__last_name', 'beneficiary__first_name'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='dividendrun',
            index=models.Index(fields=['company', 'status'], name='dividends_d_company_f61fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='dividendrun',
            index=models.Index(fields=['company', 'record_date'], name='dividends_d_company_20b70d_idx'),
        ),
        migrations.AddIndex(
            model_name='dividendallocation',
            index=models.Index(fields=['run', 'status'], name='dividends_d_run_id_ede476_idx'),
        ),
        migrations.AddIndex(
            model_name='dividendallocation',
            index=models.Index(fields=['beneficiary', 'run'], name='dividends_d_benefic_e07727_idx'),
        ),
        migrations.AddConstraint(
            model_name='dividendallocation',
            constraint=models.UniqueConstraint(fields=('run', 'beneficiary'), name='unique_allocation_per_beneficiary_per_run'),
        ),
    ]
