# Generated by Django 5.1.6 on 2026-02-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividendrun',
            name='ldt_date',
            field=models.DateField(blank=True, help_text='Last Date to Trade. Beneficiaries active on LDT qualify for dividend.', null=True),
        ),
    ]
