# Generated by Django 5.1.6 on 2026-02-08 09:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number_encrypted', models.TextField(blank=True, help_text='SA ID number – stored encrypted.')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('tax_number', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number_encrypted', models.TextField(blank=True, help_text='Bank account number – stored encrypted.')),
                ('account_type', models.CharField(blank=True, choices=[('savings', 'Savings'), ('cheque', 'Cheque / Current'), ('transmission', 'Transmission')], max_length=20)),
                ('branch_code', models.CharField(blank=True, max_length=10)),
                ('total_shares', models.PositiveIntegerField(default=0)),
                ('vested_shares', models.PositiveIntegerField(default=0)),
                ('unvested_shares', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], db_index=True, default='active', max_length=20)),
                ('employment_date', models.DateField(blank=True, null=True)),
                ('scheme_join_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.company')),
                ('user', models.OneToOneField(blank=True, help_text='Portal user account. NULL if beneficiary has no login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'beneficiaries',
                'ordering': ['last_name', 'first_name'],
                'abstract': False,
                'indexes': [models.Index(fields=['company', 'status'], name='beneficiari_company_9f3958_idx'), models.Index(fields=['company', 'last_name', 'first_name'], name='beneficiari_company_463ef3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('employee_number__gt', '')), fields=('company', 'employee_number'), name='unique_employee_per_company')],
            },
        ),
    ]
