# Generated by Django 5.1.6 on 2026-02-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='leaver_type',
            field=models.CharField(blank=True, choices=[('good', 'Good Leaver'), ('bad', 'Bad Leaver')], help_text='Set when status is TERMINATED. Good/Bad leaver affects dividend treatment.', max_length=10),
        ),
    ]
